
let pool=[], current=0, selected=[], checked=false, results=[];
const $=id=>document.getElementById(id);
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function isCorrect(q, sel){return q.options.every((o,i)=>!!o.correct===sel.includes(i));}
function initTopicFilter(){const topics=[...new Set(QUESTIONS.map(q=>q.title))].sort(); const s=$('topic'); s.innerHTML='<option value="all">All questions</option>'+topics.map(t=>`<option value="${escapeHtml(t)}">${escapeHtml(t)}</option>`).join(''); $('totalCount').textContent=QUESTIONS.length;}
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function startQuiz(){const topic=$('topic').value; let source=QUESTIONS.filter(q=>topic==='all'||q.title===topic); const n=Math.min(parseInt($('numQ').value||source.length), source.length); pool=shuffle(source).slice(0,n).map(q=>({...q, options: shuffle(q.options.map((o,idx)=>({...o, originalIndex: idx})))})); current=0; results=[]; $('setup').classList.add('hide'); $('quiz').classList.remove('hide'); $('summary').classList.add('hide'); renderQuestion();}
function renderQuestion(){selected=[]; checked=false; const q=pool[current]; $('qTitle').textContent=q.title; $('qCounter').textContent=`Question ${current+1} / ${pool.length}`; $('qType').textContent=q.type==='single'?'single choice':'multiple / true-false'; $('qText').textContent=q.question; $('feedback').className='feedback hide'; $('checkBtn').disabled=false; $('nextBtn').disabled=true; $('nextBtn').textContent=current===pool.length-1?'Finish':'Next'; $('bar').style.width=`${(current)/pool.length*100}%`; const type=q.type==='single'?'radio':'checkbox'; $('options').innerHTML=q.options.map((o,i)=>`<label class="option" id="optwrap${i}"><input type="${type}" name="answer" value="${i}" onchange="choose(${i})"><span>${escapeHtml(o.text)}</span></label>`).join('');}
window.choose=function(i){const q=pool[current]; if(checked)return; if(q.type==='single'){selected=[i]; document.querySelectorAll('input[name=answer]').forEach((el,idx)=>el.checked=idx===i);} else {const el=document.querySelector(`input[value="${i}"]`); if(el.checked){if(!selected.includes(i))selected.push(i);} else selected=selected.filter(x=>x!==i);}}
function checkAnswer(){const q=pool[current]; const ok=isCorrect(q,selected); checked=true; q.options.forEach((o,i)=>{const w=$('optwrap'+i); const chosen=selected.includes(i); w.classList.remove('correct','wrong','missed'); if(o.correct)w.classList.add('correct'); if(chosen&&!o.correct)w.classList.add('wrong'); if(!chosen&&o.correct)w.classList.add('missed');}); document.querySelectorAll('input[name=answer]').forEach(el=>el.disabled=true); const correctAnswers=q.options.filter(o=>o.correct).map(o=>o.text); $('feedback').className='feedback '+(ok?'ok':'no'); $('feedback').innerHTML= ok ? '✅ Correct!' : `❌ Not quite. Correct answer${correctAnswers.length>1?'s':''}:<br><ul>${correctAnswers.map(a=>`<li>${escapeHtml(a)}</li>`).join('')}</ul>`; results[current]={q, ok, selected:[...selected]}; $('checkBtn').disabled=true; $('nextBtn').disabled=false;}
function nextQuestion(){if(current<pool.length-1){current++;renderQuestion();}else finishQuiz();}
function finishQuiz(){const score=results.filter(r=>r&&r.ok).length; $('quiz').classList.add('hide'); $('summary').classList.remove('hide'); $('bar').style.width='100%'; $('finalScore').textContent=`${score} / ${pool.length}`; $('finalPercent').textContent=Math.round(score/pool.length*100)+'%'; const old=JSON.parse(localStorage.getItem('phy127_stats')||'{"attempts":0,"correct":0,"answered":0}'); old.attempts+=1; old.correct+=score; old.answered+=pool.length; localStorage.setItem('phy127_stats',JSON.stringify(old)); updateStats(); $('review').innerHTML=results.map((r,idx)=>{const ca=r.q.options.filter(o=>o.correct).map(o=>o.text).join('; '); return `<div class="reviewItem ${r.ok?'good':'bad'}"><b>${idx+1}. ${escapeHtml(r.q.title)}</b><br>${escapeHtml(r.q.question)}<br><span class="small">Correct: ${escapeHtml(ca)}</span></div>`}).join('');}
function updateStats(){const s=JSON.parse(localStorage.getItem('phy127_stats')||'{"attempts":0,"correct":0,"answered":0}'); $('attempts').textContent=s.attempts; $('lifetime').textContent=s.answered?Math.round(s.correct/s.answered*100)+'%':'0%';}
function resetStats(){localStorage.removeItem('phy127_stats');updateStats();}
function backHome(){$('setup').classList.remove('hide');$('quiz').classList.add('hide');$('summary').classList.add('hide');}
window.onload=()=>{initTopicFilter();updateStats();$('startBtn').onclick=startQuiz;$('checkBtn').onclick=checkAnswer;$('nextBtn').onclick=nextQuestion;$('againBtn').onclick=startQuiz;$('homeBtn').onclick=backHome;$('resetStats').onclick=resetStats;};
